version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ubc123123
      MYSQL_DATABASE: escolaUbc
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init.sql into the container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin
